### PR TITLE
Fix/form submit crash on empty fields

### LINKED ISSUE #44: Bug: App crashes when submitting an empty form
### Description

The app crashes when attempting to submit a form with empty fields. After the crash, the app becomes unresponsive. To verify the issue, check the browser's console for error messages.

### Steps to reproduce:

1. Go to https://scrow.exchange/.
2. Navigate to a route other than the root, e.g., https://scrow.exchange/create.
3. Leave all the form fields empty.
4. Click the "Generate Address" button to submit the form.
5. Observe that the app crashes.
7. Open the browser's console (press F12 or right-click and select "Inspect" -> "Console") to check for error messages.

Image

### Tested browsers

Brave, Chrome, Firefox

### Possible solution

- Required Field Validation: Before submitting the form, check that all required fields are filled. If not, display an error message and prevent submission.
- Error Handling: Ensure that errors during submission are properly handled, avoiding app crashes and informing the user about what went wrong.
- Error Messages: Use toast notifications to display error messages, helping the user quickly identify what needs to be fixed.

### PR DESCRIPTION
**Pull request by gabriel-cmps**
Closes #44 

Standardize and personalize input field error messages, providing a clearer and more intuitive user experience. Additionally, ensure that optional fields are only validated when truly necessary, according to the context.

Instead of displaying errors through toasts (which can be intrusive or easily missed), validation now occurs directly within the input fields themselves, in a more user-friendly and contextual way. This allows users to correct issues immediately, making the interaction smoother and more efficient.

Previously, the validations inside input components were ineffective, they didn’t prevent the form from being submitted even when fields were invalid or empty. Now, these validations are meaningful and directly integrated with the form logic, actually preventing submission when required conditions aren’t met.

### Preview
Screenshot from 2025-04-22 00-05-08

### CODE REVIEW

**Comment by storopoli** [comment]
This is nice! Thanks for the PR. Will review it over the weekend.

**Comment by gabriel-cmps** [comment]
> This is nice! Thanks for the PR. Will review it over the weekend.

You're welcome! While I was reviewing the settings page, I noticed a couple of logic issues:

1. **The form doesn't crash**, but it's possible to submit an **empty or invalid URL**, which could lead to unexpected behavior.
2. **The `Save Settings` button is currently non-functional**, since the esplora endpoint is being updated directly via `onInput`, making the button redundant.

Here’s what I found in the code:

```rust
PrimaryButton {
    onclick: move |_| {}, // No logic here
    text: "Save Settings",
}
```

And the esplora URL is updated immediately on input:

```rust
let mut validate_url = move |input: &str| {
    if input.is_empty() {
        *has_error.write() = false;
        *ESPLORA_ENDPOINT.write() = input.to_string();
        return;
    }

    let is_valid = input.starts_with("http://") || input.starts_with("https://");
    *has_error.write() = !is_valid;
    *ESPLORA_ENDPOINT.write() = input.to_string(); // Happens immediately
};
```
Would you be okay if I include a fix for these issues in this same PR?

**Comment by luisschwab** [comment]
Looking good @gabriel-cmps, you're just missing formatting.

**Comment by gabriel-cmps** [comment]
> Looking good @gabriel-cmps, you're just missing formatting.

Done.

File: src/validation.rs [hunk 1]
```diff
@@ -0,0 +1,158 @@
...
+            ValidationField::TimelockHours => "Hours should be between 0 and 23.",
+        }
+    }
+}
+
+pub(crate) fn validate_input(
+    input: &str,
+    field: ValidationField,
+    required: bool,
+) -> Option<String> {
```
Comment (storopoli) [inline src/validation.rs:112]: I find that a function named validate that returns `None` if the thing is validated somewhat unintuitive.

**Review by storopoli — CHANGES_REQUESTED** [review]
I think we should deal with validation and empty fields similar to error handling.

Having something like: `Result<(), Error>` where the `Display` for that error is the user feedback to be rendered below the input field/dials etc.

What do you think @gabriel-cmps? I think that the current approach is less maintainable and extendable and looks very ad-hoc, complex, inflexible interface.

Cc @luisschwab

**Comment by luisschwab** [comment]
> I think we should deal with validation and empty fields similar to error handling.

I agree. It's better to return a `Result<_, Error>` and extend the `Error` enum on `error.rs`.

**Comment by gabriel-cmps** [comment]
> I think we should deal with validation and empty fields similar to error handling.
> 
> Having something like: `Result<(), Error>` where the `Display` for that error is the user feedback to be rendered below the input field/dials etc.
> 
> What do you think @gabriel-cmps? I think that the current approach is less maintainable and extendable and looks very ad-hoc, complex, inflexible interface.
> 
> Cc @luisschwab

I agree. I will make those improvements.

**Comment by storopoli** [comment]
> > I agree. It's better to return a `Result<_, Error>` and extend the `Error` enum on `error.rs`.
> 
> I liked your idea, but I think creating an enum called ValidationError specifically for the validation would be better than extending the Error enum in error.rs. What do you think about creating this enum inside the error.rs file?
> 
> Cc @storopoli

Yes sounds good. As long as it is an `Error` inside the `error.rs`. It makes sense to decouple from the other `error::Error`.

File: src/components/broadcast.rs [hunk 2]
```diff
@@ -6,8 +6,8 @@ use dioxus::prelude::*;
 #[cfg(debug_assertions)]
 use dioxus::logger::tracing::{info, trace};
 
-use crate::ESPLORA_ENDPOINT;
 use crate::esplora::{broadcast_transaction, create_client};
+use crate::{ESPLORA_ENDPOINT, validation::*};
```
Comment (storopoli) [inline src/components/broadcast.rs:10]: no globbing import the stuff explicitly, this is not Python...
We only glob preludes like `dioxus::prelude::*` or in tests with `use super::*`

File: src/components/combine.rs [hunk 3]
```diff
@@ -12,6 +12,7 @@ use crate::{
     scripts::{escrow_scripts, escrow_spend_info},
     sign::combine_signatures,
     util::{days_to_blocks, hours_to_blocks, parse_escrow_type, parse_npub},
+    validation::*,
```
Comment (storopoli) [inline src/components/combine.rs:15]: no globbing import the stuff explicitly, this is not Python...
We only glob preludes like `dioxus::prelude::*` or in tests with `use super::*`

File: src/components/create.rs [hunk 4]
```diff
@@ -15,6 +15,7 @@ use crate::{
         P2TR_TX_VBYTE_C, days_to_blocks, hours_to_blocks, npub_to_address, parse_network,
         parse_npub,
     },
+    validation::*,
```
Comment (storopoli) [inline src/components/create.rs:18]: no globbing import the stuff explicitly, this is not Python...
We only glob preludes like `dioxus::prelude::*` or in tests with `use super::*`

File: src/components/input.rs [hunk 5]
```diff
@@ -1,16 +1,15 @@
...
 #[cfg(debug_assertions)]
 use dioxus::logger::tracing::trace;
-use secp256k1::schnorr;
 
 use crate::{
     ESPLORA_ENDPOINT, NETWORK,
     esplora::FeeEstimate,
-    util::{npub_to_address, parse_network, parse_npub, parse_nsec},
+    util::{npub_to_address, parse_network, parse_npub},
+    validation::*,
```
Comment (storopoli) [inline src/components/input.rs:12]: no globbing import the stuff explicitly, this is not Python...
We only glob preludes like `dioxus::prelude::*` or in tests with `use super::*`

File: src/components/settings.rs [hunk 6]
```diff
@@ -5,7 +5,7 @@ use dioxus::prelude::*;
 #[cfg(debug_assertions)]
 use dioxus::logger::tracing::trace;
 
-use crate::{ESPLORA_ENDPOINT, NETWORK};
+use crate::{ESPLORA_ENDPOINT, NETWORK, validation::*};
```
Comment (storopoli) [inline src/components/settings.rs:8]: no globbing import the stuff explicitly, this is not Python...
We only glob preludes like `dioxus::prelude::*` or in tests with `use super::*`

File: src/components/sign.rs [hunk 7]
```diff
@@ -13,6 +13,7 @@ use crate::{
     util::{
         days_to_blocks, hours_to_blocks, parse_escrow_type, parse_network, parse_npub, parse_nsec,
     },
+    validation::*,
```
Comment (storopoli) [inline src/components/sign.rs:16]: no globbing import the stuff explicitly, this is not Python...
We only glob preludes like `dioxus::prelude::*` or in tests with `use super::*`

File: src/components/spend.rs [hunk 8]
```diff
@@ -12,6 +12,7 @@ use crate::{
     sign::sign_resolution_tx,
     tx::resolution_tx,
     util::{P2TR_TX_VBYTE_KEY_PATH, parse_network, parse_nsec},
+    validation::*,
```
Comment (storopoli) [inline src/components/spend.rs:15]: no globbing import the stuff explicitly, this is not Python...
We only glob preludes like `dioxus::prelude::*` or in tests with `use super::*`

File: src/error.rs [hunk 9]
```diff
@@ -33,3 +33,42 @@ pub(crate) enum Error {
...
+    InvalidAddress,
+
+    #[error("Invalid URL format. Should start with http:// or https://.")]
+    InvalidUrl,
+
+    #[error("Days should be between 0 and 1,000.")]
+    InvalidTimelockDays,
+
+    #[error("Hours should be between 0 and 23.")]
+    InvalidTimelockHours,
```
Comment (storopoli) [inline src/error.rs:73]: All these `ValidationError` variants can carry valuable information and not be so opaque.

example for types that implement `Display`:

```rs
#[error("Hours should be between 0 and 23. Got: {0}")]
    InvalidTimelockHours(u8),
```

example for types that implement `Debug`:

```
#[error("Invalid Bitcoin address format. Please check and try again. Got: {0:?}")]
    InvalidAddress(TypeThatHasDebugOnly),
```

Prefer `Display` over `Debug` in these transparent hints.

File: src/validation.rs [hunk 10]
```diff
@@ -0,0 +1,82 @@
...
+    Txid,
+    Transaction,
+    Signature,
+    Address,
+    Url,
+    TimelockDays,
+    TimelockHours,
+}
+
+pub(crate) fn validate_input(
```
Comment (storopoli) [inline src/validation.rs:23]: docstring

File: src/validation.rs [hunk 11]
```diff
@@ -0,0 +1,82 @@
+use crate::NETWORK;
+use crate::error::ValidationError;
+use crate::util::{parse_network, parse_npub, parse_nsec};
+use bitcoin::{Address, Amount, FeeRate, Transaction, Txid};
+use dioxus::signals::Readable;
+use secp256k1::schnorr;
+
+#[derive(Debug)]
+pub(crate) enum ValidationField {
```
Comment (storopoli) [inline src/validation.rs:9]: docstring

File: src/validation.rs [hunk 12]
```diff
@@ -0,0 +1,82 @@
+use crate::NETWORK;
```
Comment (storopoli) [inline src/validation.rs:1]: module-level docstrings

File: src/error.rs [hunk 13]
```diff
@@ -33,3 +33,42 @@ pub(crate) enum Error {
     #[error("Expected exactly one funding transaction")]
     ExpectedOneFundingTransaction,
 }
+
+#[derive(Debug, Error)]
+pub(crate) enum ValidationError {
```
Comment (storopoli) [inline src/error.rs:38]: docstring

File: src/error.rs (hunk 9 above)
Comment (gabriel-cmps) [reply src/error.rs:73]: I understand your point of view, but in my opinion, this isn’t good for UX at all. Since it’s a message that will be shown to the user, it doesn’t make any sense to display something like "Got:", because the user is already seeing what they’re typing into the input, in addition to it not being a friendly message. For debugging purposes, however, it could be useful to include something like that.

File: src/components/broadcast.rs (hunk 2 above)
Comment (gabriel-cmps) [reply src/components/broadcast.rs:10]: Done!

File: src/error.rs (hunk 9 above)
Comment (storopoli) [reply src/error.rs:77]: Ok fair point!

**Review by storopoli — APPROVED** [review]
ACK a230bac1f5f890efb55f4d8280dbdf385356344a
